---
title: "HW1"
author: "B04303061 丁立恆"
date: "2021/3/11"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

```{r, include=FALSE}
library(ggplot2)
library(tidyverse)
library(rWishart)
```

#Q1
```{r}
rejection1 <- function(a, b, fx){
  while(TRUE){
    x <- runif(1, a, b)
    y <- 2 * rexp(1,0.65)
    
    if(y < fx(x)) return(x)
  }
}

fx1 <- function(x){
  beta(3,2) * x^3 * (1-x)^2
}

beta3_2 <- sapply(1:1000, function(x){
  rejection1(0, 1, fx1)
})

hist(beta3_2, breaks = seq(0,1,0.05), freq = FALSE, main = "Beta(3,2)", xlab="x")
lines(seq(0, 1, 0.01), dbeta(seq(0, 1, 0.01), 3, 2))
```

#Q2
```{r}
R <- 1

rejection2 <- function(R, fx){
  while(TRUE){
    x <- runif(1, 0, 2) - 1
    y <- runif(1, 0, 1)
    
    if(y < fx(R, x)) return(x)
  }
}
  
fx2 <- function(R, x){
  r <- R
  2/(pi*r^2) * sqrt(r^2 - x^2)
}

dist2 <- sapply(1:1000, function(x){
  rejection2(R, fx2)
})

hist(dist2, breaks = seq(-1, 1, 0.1), freq = FALSE, main = "Q2", xlab="x")
lines(seq(-R, R, 0.05), fx2(R, seq(-R, R, 0.05)))
```

#Q3
```{r}
alpha <- 2
beta <- 4
hist(alpha*runif(1000,0,1)^(-1/beta), breaks = 30,freq = FALSE, main = "Pareto(2, 4)", xlab = "X")
lines(seq(0, 10, 0.1), beta*alpha^beta/(seq(0, 10, 0.1)^(beta+1)))
```

#Q4
```{r}
x1 <- rnorm(5000, 0, 1)
x2 <- rnorm(5000, 4, 2)
bool_vec <- sample(c(TRUE,FALSE),5000,replace=TRUE,prob=c(0.5,0.5))
df <- data.frame(type = c(rep("convolution", 5000), rep("mixture", 5000)),
                value = c(x1+x2, c(x1[bool_vec],x2[!bool_vec])))
Q4 <- df %>% ggplot(aes(x=value, color=type))+
  geom_density()+
  ggtitle("Convolution vs. mixture normal")+
  xlab("X")+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank())

Q4
```

#Q5
```{r}
N <- 50
K <- 20
n <- 10

prob_for_hyper <- sapply(1:(min(n,K)+1),function(x){
  a <- x - 1
  choose(20, a) * choose(N-K, n-a) / choose(N, n)
})
prob_cum = cumsum(prob_for_hyper)
indicator = sapply(1:1000, function(x){
  sum(prob_cum < runif(1, 0, 1)) 
})
#layout(matrix(c(1,1,2,2), 2, 2, byrow = TRUE), respect = TRUE)
hist(indicator, breaks = seq(0, n, 1), freq = FALSE, 
     main = "hypergeometric(50, 20, 10) empirical", xlab = "X")
hist(rhyper(1000, K, N-K, n), breaks = seq(0, n, 1), freq = FALSE, 
     main = "hypergeometric(50, 20, 10) theoretical", xlab = "X")
```
